# Generated by Django 5.2 on 2025-04-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('course_slug', models.SlugField(verbose_name='Course Slug')),
                ('course_description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('course_is_active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Is Active?')),
                ('course_is_featured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Is Featured?')),
                ('course_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('course_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('seo_course_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Course Title (60 Characters Long)')),
                ('seo_course_keywords', models.TextField(blank=True, null=True, verbose_name='SEO for Course Keywords, Separated by Commas')),
                ('seo_course_description', models.TextField(blank=True, null=True, verbose_name='SEO Course Description (160 Characters Long)')),
            ],
            options={
                'ordering': ('-course_created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=50, verbose_name='Topic Title')),
                ('topic_slug', models.SlugField(max_length=55, verbose_name='Topic Slug')),
                ('topic_description', models.TextField(blank=True, null=True, verbose_name='Topic Description')),
                ('topic_image', models.ImageField(blank=True, null=True, upload_to='topics/')),
                ('topic_is_active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, verbose_name='Is Active?')),
                ('topic_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('topic_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('meta_topic_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Topic Title (60 Characters Long)')),
                ('meta_topic_keywords', models.TextField(blank=True, null=True, verbose_name='SEO Topic Keywords, Separated by Commas')),
                ('meta_topic_description', models.TextField(blank=True, null=True, verbose_name='SEO Topic Description (160 characters long)')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=255, verbose_name='Lecture Title')),
                ('lecture_slug', models.SlugField(verbose_name='Lecture Slug')),
                ('lecture_description', models.TextField(blank=True, null=True, verbose_name='Lecture Description')),
                ('lecture_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('lecture_video', models.CharField(blank=True, max_length=150, null=True, verbose_name='Video ID')),
                ('lecture_previewable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Is Previewable?')),
                ('lecture_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('lecture_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('seo_lecture_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Lecture Title (60 Characters Long)')),
                ('seo_lecture_keyword', models.TextField(blank=True, null=True, verbose_name='SEO Lecture Keywords, Separated by Comma')),
                ('seo_lecture_description', models.TextField(blank=True, null=True, verbose_name='SEO Lecture Description (160 Characters Long)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_lectures', models.ManyToManyField(blank=True, to='courses.lecture')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('completed_quizzes', models.ManyToManyField(blank=True, to='courses.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_topic',
            field=models.ManyToManyField(to='courses.topic', verbose_name='Course Topic'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
