# Generated by Django 5.2 on 2025-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='quiz_score',
            field=models.FloatField(default=0.0),
        ),
    ]
